_target_: src.scenario.gz_experiments.PushingObjectSACScenario

simulator: ~ simulator
running_objective: ~ running_objective
device: "cpu"
total_timesteps: 6000
buffer_size: 25000
gamma: 0.95
tau: 0.005
batch_size: 256
learning_starts: 1000
policy_lr: 3.0e-4
q_lr: 1.0e-3
policy_frequency: 50
target_network_frequency: 50
alpha: 0.2
autotune: True
evaluation_only: False
reset_rb_each_task: False
checkpoint_dirpath: null
evaluation_episode_number: 30
